from __future__ import annotations

import hashlib
import importlib.util
import json
from pathlib import Path
import copy
import sys
import tempfile
import unittest
from unittest import mock
import zlib


REPOSITORY = Path(__file__).resolve().parents[1]
SCRIPT = REPOSITORY / "scripts" / "build-incompressible-precompressed-development.py"
CONFIG = REPOSITORY / "config" / "incompressible-precompressed-gates-v1.json"
SPEC = importlib.util.spec_from_file_location("incompressible_precompressed_builder", SCRIPT)
if SPEC is None or SPEC.loader is None:
    raise RuntimeError("could not load incompressible/precompressed builder")
MODULE = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(MODULE)


class IncompressiblePrecompressedBuilderTests(unittest.TestCase):
    def test_tool_resolver_receives_the_frozen_baseline_config_contract(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            resolved = {}
            for tool_id in MODULE.TOOL_FOR_PROFILE.values():
                path = root / tool_id
                path.write_bytes(tool_id.encode("ascii"))
                path.chmod(0o755)
                resolved[tool_id] = {
                    "path": str(path),
                    "version": f"{tool_id} fixture",
                    "binary_size_bytes": path.stat().st_size,
                    "binary_sha256": MODULE.sha256_file(path),
                }
            with mock.patch.object(
                MODULE.BASELINE, "resolve_tools", return_value=resolved
            ) as resolver:
                paths, public = MODULE.safe_tool_records(root / "tools")
            resolver.assert_called_once()
            config, config_path, tools_root = resolver.call_args.args
            self.assertEqual(
                config["name"], "text-source-baseline-toolchain-v1"
            )
            self.assertEqual(config_path, MODULE.BASELINE.DEFAULT_CONFIG)
            self.assertEqual(tools_root, root / "tools")
            self.assertEqual(set(paths), set(MODULE.TOOL_FOR_PROFILE.values()))
            self.assertIn("python-zipfile", public)
            self.assertIn("corpus-builder", public)

    def toolchain_fixture(self) -> dict[str, dict[str, object]]:
        digest = "a" * 64
        tools = {
            tool_id: {
                "version": f"{tool_id} fixture",
                "binary_size_bytes": 1,
                "binary_sha256": digest,
            }
            for tool_id in MODULE.TOOL_FOR_PROFILE.values()
        }
        tools["python-zipfile"] = {
            "python": "3.12.12",
            "zlib_runtime": "1.2.13",
            "executable_size_bytes": 1,
            "executable_sha256": digest,
            "runner_sha256": digest,
        }
        tools["corpus-builder"] = {
            "implementation": "CPython",
            "script_sha256": digest,
            "stream_chunk_bytes": MODULE.CHUNK_SIZE,
        }
        return tools

    def complete_corpus_fixture(self, root: Path) -> tuple[Path, Path]:
        output = root / "corpus"
        output.mkdir()
        (output / "items").mkdir()
        (output / "receipts").mkdir()
        generated_tasks = []
        for index in range(31):
            item_id = f"generated-{index:02d}"
            generated_tasks.append(
                {
                    "task_id": item_id,
                    "family_id": "shake256-uniform",
                    "kind": "generated",
                    "item_id": item_id,
                    "output_filename": f"{item_id}.bin",
                    "planned_bytes": index % 3,
                    "license": "CC0-1.0 generated bytes",
                    "generation": {
                        "algorithm": "counter-mode-shake256-v1",
                        "domain": MODULE.PLANNER.DOMAIN,
                        "item_id": item_id,
                        "block_bytes": MODULE.CHUNK_SIZE,
                        "counter_encoding": "uint64 little-endian",
                    },
                }
            )
        precompressed_tasks = []
        for index in range(18):
            item_id = f"precompressed-{index:02d}"
            precompressed_tasks.append(
                {
                    "task_id": item_id,
                    "family_id": "licensed-precompressed-source",
                    "kind": "precompressed",
                    "item_id": item_id,
                    "output_filename": f"{item_id}.gz",
                    "license": "fixture-license",
                    "source": {
                        "source_id": f"source-{index:02d}",
                        "bundle_path": f"source-{index:02d}.bin",
                        "bundle_size_bytes": index + 1,
                        "bundle_sha256": f"{index + 1:064x}",
                        "format": "source-bundle-v1",
                    },
                    "precompression_profile_id": "gzip-9",
                }
            )
        plan = {
            "schema_version": 1,
            "name": "fixture-incompressible-plan",
            "bindings": {"repository_commit": "c" * 40},
            "precompression_profiles": {
                "gzip-9": {
                    "compress": ["gzip", "-9", "$SOURCE"],
                    "decompress": ["gzip", "-d", "$PAYLOAD"],
                }
            },
            "tasks": generated_tasks + precompressed_tasks,
            "claim_ceiling": "fixture development evidence only",
        }
        plan_path = root / "plan.json"
        plan_path.write_bytes(MODULE.json_bytes(plan))
        plan_sha256 = MODULE.sha256_file(plan_path)
        tools_public = self.toolchain_fixture()
        MODULE.write_json_atomic(
            output / "attempt.json",
            {
                "schema_version": 1,
                "name": "incompressible-precompressed-development-corpus-attempt-v1",
                "plan_sha256": plan_sha256,
                "repository_commit": plan["bindings"]["repository_commit"],
                "toolchain": tools_public,
                "timeout_seconds_per_precompression_operation": 60.0,
                "axiom_wins": 0,
                "claim_ceiling": plan["claim_ceiling"],
            },
        )
        receipts = []
        for task in generated_tasks:
            receipts.append(
                MODULE.materialize_generated(
                    work=output, task=task, plan_sha256=plan_sha256
                )
            )
        process = {
            "command": ["fixture"],
            "returncode": 0,
            "stdout": MODULE.stream_commitment(b""),
            "stderr": MODULE.stream_commitment(b""),
        }
        for index, task in enumerate(precompressed_tasks):
            item_path = output / "items" / task["output_filename"]
            item_path.write_bytes(bytes([index]) * (index + 1))
            receipt = MODULE.precompressed_receipt(
                task=task,
                item_path=item_path,
                plan_sha256=plan_sha256,
                tools_public=tools_public,
                compression=process,
                decompression=process,
                profiles=plan["precompression_profiles"],
            )
            MODULE.write_json_atomic(
                output / "receipts" / f"{task['task_id']}.json", receipt
            )
            receipts.append(receipt)
        receipts_sha256 = MODULE.receipt_manifest(output, receipts)
        manifest = MODULE.build_manifest(
            plan=plan,
            plan_sha256=plan_sha256,
            receipts=receipts,
            tools_public=tools_public,
            receipts_sha256=receipts_sha256,
        )
        MODULE.write_json_atomic(output / "manifest.json", manifest)
        MODULE.write_json_atomic(
            output / "receipt.json",
            {
                "schema_version": 1,
                "name": "incompressible-precompressed-development-corpus-receipt-v1",
                "plan_sha256": plan_sha256,
                "manifest_sha256": MODULE.sha256_file(output / "manifest.json"),
                "receipt_manifest_sha256": receipts_sha256,
                "item_count": 49,
                "generated_item_count": 31,
                "precompressed_item_count": 18,
                "axiom_wins": 0,
                "claim_ceiling": plan["claim_ceiling"],
            },
        )
        return output, plan_path

    def test_complete_corpus_reconstructs_and_rejects_attempt_tampering(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            output, plan_path = self.complete_corpus_fixture(Path(raw))
            verified = MODULE.validate_corpus(output, plan_path)
            self.assertTrue(verified["verified"])
            self.assertEqual(verified["item_count"], 49)
            attempt_path = output / "attempt.json"
            attempt = json.loads(attempt_path.read_bytes())
            attempt["timeout_seconds_per_precompression_operation"] = False
            attempt_path.write_bytes(MODULE.json_bytes(attempt))
            with self.assertRaisesRegex(ValueError, "corpus identity differs"):
                MODULE.validate_corpus(output, plan_path)

    def test_complete_corpus_rejects_a_malformed_process_commitment(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            output, plan_path = self.complete_corpus_fixture(Path(raw))
            receipt_path = output / "receipts" / "precompressed-00.json"
            receipt = json.loads(receipt_path.read_bytes())
            receipt["compression"]["stdout"]["extra"] = 1
            receipt_path.write_bytes(MODULE.json_bytes(receipt))
            with self.assertRaisesRegex(ValueError, "process differs"):
                MODULE.validate_corpus(output, plan_path)

    def test_toolchain_identity_is_strict_and_tamper_evident(self) -> None:
        fixture = self.toolchain_fixture()
        MODULE.validate_toolchain(fixture)
        cases = []
        extra = copy.deepcopy(fixture)
        extra["unexpected"] = {}
        cases.append(extra)
        boolean_size = copy.deepcopy(fixture)
        boolean_size["gzip"]["binary_size_bytes"] = True
        cases.append(boolean_size)
        uppercase_digest = copy.deepcopy(fixture)
        uppercase_digest["python-zipfile"]["runner_sha256"] = "A" * 64
        cases.append(uppercase_digest)
        wrong_chunk = copy.deepcopy(fixture)
        wrong_chunk["corpus-builder"]["stream_chunk_bytes"] = MODULE.CHUNK_SIZE - 1
        cases.append(wrong_chunk)
        for case in cases:
            with self.subTest(case=case):
                with self.assertRaisesRegex(ValueError, "toolchain|tool identity|ZIP|builder"):
                    MODULE.validate_toolchain(case)

    def test_stream_commitments_have_an_exact_schema(self) -> None:
        valid = {"bytes": 0, "sha256": hashlib.sha256(b"").hexdigest()}
        self.assertTrue(MODULE.is_stream_commitment(valid))
        self.assertFalse(MODULE.is_stream_commitment(valid | {"extra": 1}))
        self.assertFalse(
            MODULE.is_stream_commitment({"bytes": False, "sha256": valid["sha256"]})
        )
        self.assertFalse(
            MODULE.is_stream_commitment({"bytes": 0, "sha256": valid["sha256"].upper()})
        )

    def test_counter_mode_shake_is_exact_and_domain_separated(self) -> None:
        first = MODULE.shake_block("domain-a", "item-a", 0, 1024)
        self.assertEqual(len(first), 1024)
        self.assertEqual(first, MODULE.shake_block("domain-a", "item-a", 0, 1024))
        self.assertNotEqual(first, MODULE.shake_block("domain-b", "item-a", 0, 1024))
        self.assertNotEqual(first, MODULE.shake_block("domain-a", "item-b", 0, 1024))
        self.assertNotEqual(first, MODULE.shake_block("domain-a", "item-a", 1, 1024))
        with self.assertRaisesRegex(ValueError, "outside protocol"):
            MODULE.shake_block("domain", "item", -1, 1)

    def test_generated_item_is_resumable_and_recipe_tamper_evident(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            task = {
                "task_id": "fixture-shake",
                "family_id": "shake256-uniform",
                "kind": "generated",
                "item_id": "fixture-shake",
                "output_filename": "fixture.bin",
                "planned_bytes": 1024 * 1024 + 17,
                "license": "CC0-1.0 generated bytes",
                "generation": {
                    "algorithm": "counter-mode-shake256-v1",
                    "domain": MODULE.PLANNER.DOMAIN,
                    "item_id": "fixture-shake",
                    "block_bytes": 1024 * 1024,
                    "counter_encoding": "uint64 little-endian",
                },
            }
            receipt = MODULE.materialize_generated(
                work=root, task=task, plan_sha256="a" * 64
            )
            self.assertTrue(receipt["exact_generation_size"])
            self.assertEqual(receipt["bytes"], task["planned_bytes"])
            self.assertEqual(
                receipt,
                MODULE.materialize_generated(
                    work=root, task=task, plan_sha256="a" * 64
                ),
            )
            item = root / "items" / "fixture.bin"
            payload = bytearray(item.read_bytes())
            payload[-1] ^= 1
            item.write_bytes(payload)
            with self.assertRaisesRegex(ValueError, "generated item identity differs"):
                MODULE.materialize_generated(
                    work=root, task=task, plan_sha256="a" * 64
                )

    def test_deceptive_layouts_and_magic_spoof_are_exact(self) -> None:
        self.assertEqual(MODULE.deceptive_kind("random-first", 0), "random")
        self.assertEqual(MODULE.deceptive_kind("random-first", 16), "zero")
        self.assertEqual(MODULE.deceptive_kind("random-middle", 32), "random")
        self.assertEqual(MODULE.deceptive_kind("random-last", 63), "random")
        self.assertEqual(
            MODULE.deceptive_kind("alternating-random-zero-1mib", 1), "zero"
        )
        self.assertEqual(MODULE.deceptive_kind("sampler-blind-spots", 31), "text")
        task = {
            "planned_bytes": 1024,
            "item_id": "magic-fixture",
            "generation": {
                "algorithm": "magic-spoofed-counter-mode-shake256-v1",
                "domain": MODULE.PLANNER.DOMAIN,
                "item_id": "magic-fixture",
                "block_bytes": 1024,
                "magic_id": "gzip",
                "magic_prefix_hex": "1f8b0800",
            },
        }
        payload = b"".join(MODULE.generated_chunks(task))
        self.assertEqual(len(payload), 1024)
        self.assertTrue(payload.startswith(bytes.fromhex("1f8b0800")))

    def test_zip_profile_is_deterministic_streaming_and_exact(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            source = root / "source.bin"
            source.write_bytes((b"deterministic ZIP fixture\n" * 10_000) + bytes(range(256)))
            first = root / "first.zip"
            second = root / "second.zip"
            MODULE.zip_compress(source, first)
            MODULE.zip_compress(source, second)
            self.assertEqual(first.read_bytes(), second.read_bytes())
            restored = root / "restored.bin"
            MODULE.zip_decompress(first, restored)
            self.assertEqual(source.read_bytes(), restored.read_bytes())

    def test_zip_decoder_rejects_a_roundtrippable_non_profile_archive(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            source = root / "source.bin"
            source.write_bytes(b"roundtrippable but wrong ZIP profile" * 100)
            wrong_method = root / "stored.zip"
            with MODULE.zipfile.ZipFile(
                wrong_method, "w", compression=MODULE.zipfile.ZIP_STORED
            ) as archive:
                info = MODULE.zipfile.ZipInfo(
                    "input.bin", date_time=(1980, 1, 1, 0, 0, 0)
                )
                info.compress_type = MODULE.zipfile.ZIP_STORED
                info.create_system = 0
                info.external_attr = 0x20
                archive.writestr(info, source.read_bytes())
            with self.assertRaisesRegex(ValueError, "metadata differs"):
                MODULE.zip_decompress(wrong_method, root / "restored.bin")

            archive_comment = root / "comment.zip"
            MODULE.zip_compress(source, archive_comment)
            with MODULE.zipfile.ZipFile(archive_comment, "a") as archive:
                archive.comment = b"not permitted"
            with self.assertRaisesRegex(ValueError, "metadata differs"):
                MODULE.zip_decompress(archive_comment, root / "comment-restored.bin")

    def test_precompressed_zip_receipt_roundtrips_and_detects_payload_edit(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            source_corpus = root / "source-corpus"
            source_corpus.mkdir()
            source = source_corpus / "fixture.axsrc"
            source.write_bytes(b"licensed source fixture\n" * 4096)
            task = {
                "task_id": "precompressed-fixture-zip",
                "family_id": "licensed-precompressed-source",
                "kind": "precompressed",
                "item_id": "precompressed-fixture-zip",
                "output_filename": "fixture.zip",
                "license": "fixture-license",
                "source": {
                    "source_id": "fixture-source",
                    "bundle_path": source.name,
                    "bundle_size_bytes": source.stat().st_size,
                    "bundle_sha256": hashlib.sha256(source.read_bytes()).hexdigest(),
                    "format": "source-bundle-v1",
                },
                "precompression_profile_id": "zip-deflate-9",
            }
            config = json.loads(CONFIG.read_text(encoding="utf-8"))
            profiles = config["precompression_profiles"]
            python_path = Path(sys.executable).resolve()
            tools_public = {
                "python-zipfile": {
                    "python": sys.version.split()[0],
                    "zlib_runtime": zlib.ZLIB_RUNTIME_VERSION,
                    "executable_size_bytes": python_path.stat().st_size,
                    "executable_sha256": MODULE.sha256_file(python_path),
                    "runner_sha256": MODULE.sha256_file(SCRIPT),
                }
            }
            work = root / "work"
            receipt = MODULE.materialize_precompressed(
                work=work,
                source_corpus=source_corpus,
                task=task,
                plan_sha256="b" * 64,
                tools={},
                tools_public=tools_public,
                profiles=profiles,
                timeout_seconds=10.0,
            )
            self.assertTrue(receipt["exact_roundtrip"])
            self.assertEqual(receipt["compression"]["returncode"], 0)
            self.assertEqual(
                receipt,
                MODULE.materialize_precompressed(
                    work=work,
                    source_corpus=source_corpus,
                    task=task,
                    plan_sha256="b" * 64,
                    tools={},
                    tools_public=tools_public,
                    profiles=profiles,
                    timeout_seconds=10.0,
                ),
            )
            item = work / "items" / "fixture.zip"
            payload = bytearray(item.read_bytes())
            payload[-1] ^= 1
            item.write_bytes(payload)
            with self.assertRaisesRegex(ValueError, "receipt differs"):
                MODULE.materialize_precompressed(
                    work=work,
                    source_corpus=source_corpus,
                    task=task,
                    plan_sha256="b" * 64,
                    tools={},
                    tools_public=tools_public,
                    profiles=profiles,
                    timeout_seconds=10.0,
                )


if __name__ == "__main__":
    unittest.main()
