use sha2::{Digest, Sha256};

pub const MIN_PROBABILITY: u16 = 64;
pub const MAX_PROBABILITY: u16 = 65_472;
const INITIAL_PROBABILITY: u16 = 32_768;
const TABLE_LENGTH: usize = 65_536;
const Q24_BITS: u32 = 24;

/// Canonical integer-only `-log2(q / 65536)` lookup in Q24 units.
///
/// Fractional `log2` bits are generated by repeated squaring. Truncating the
/// logarithm makes the resulting loss conservative by less than one Q24 unit.
#[derive(Clone)]
pub struct LossTable {
    values: Box<[u32; TABLE_LENGTH]>,
}

impl LossTable {
    #[must_use]
    pub fn generate() -> Self {
        let values = vec![0_u32; TABLE_LENGTH].into_boxed_slice();
        let mut values: Box<[u32; TABLE_LENGTH]> = values
            .try_into()
            .unwrap_or_else(|_| unreachable!("loss table length is a constant"));
        for q in 1_u32..TABLE_LENGTH as u32 {
            values[q as usize] = loss_q24(q);
        }
        // Probability zero is forbidden and `get(0)` rejects it. Keep the
        // unused slot equal to q=1 solely to make the full-table digest stable.
        values[0] = values[1];
        Self { values }
    }

    #[must_use]
    pub fn get(&self, probability_of_observed_bit: u32) -> Option<u32> {
        if !(1..TABLE_LENGTH as u32).contains(&probability_of_observed_bit) {
            return None;
        }
        Some(self.values[probability_of_observed_bit as usize])
    }

    #[must_use]
    pub fn sha256(&self) -> [u8; 32] {
        let mut digest = Sha256::new();
        for value in self.values.iter() {
            digest.update(value.to_le_bytes());
        }
        digest.finalize().into()
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Probability {
    probability_of_one: u16,
}

impl Default for Probability {
    fn default() -> Self {
        Self {
            probability_of_one: INITIAL_PROBABILITY,
        }
    }
}

impl Probability {
    #[must_use]
    pub fn probability_of_one(self) -> u16 {
        self.probability_of_one
    }

    #[must_use]
    pub fn probability_of(self, bit: bool) -> u32 {
        if bit {
            u32::from(self.probability_of_one)
        } else {
            65_536 - u32::from(self.probability_of_one)
        }
    }

    /// Update after charging the prediction held before observing `bit`.
    pub fn update(&mut self, bit: bool, rate_shift: u32) {
        assert!(
            rate_shift < i32::BITS,
            "probability rate shift must fit i32"
        );
        let current = i32::from(self.probability_of_one);
        let target = if bit { 65_536_i32 } else { 0_i32 };
        let updated = current + ((target - current) >> rate_shift);
        self.probability_of_one =
            updated.clamp(i32::from(MIN_PROBABILITY), i32::from(MAX_PROBABILITY)) as u16;
    }
}

fn loss_q24(q: u32) -> u32 {
    debug_assert!((1..65_536).contains(&q));
    let exponent = 31 - q.leading_zeros();
    let mut normalized_q63 = u128::from(q) << (63 - exponent);
    let mut fractional_q24 = 0_u32;

    for output_bit in (0..Q24_BITS).rev() {
        normalized_q63 = (normalized_q63 * normalized_q63) >> 63;
        if normalized_q63 >= (2_u128 << 63) {
            normalized_q63 >>= 1;
            fractional_q24 |= 1_u32 << output_bit;
        }
    }

    ((16 - exponent) << Q24_BITS) - fractional_q24
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn powers_of_two_have_exact_integer_losses() {
        for exponent in 0..16_u32 {
            let q = 1_u32 << exponent;
            assert_eq!(loss_q24(q), (16 - exponent) << Q24_BITS);
        }
    }

    #[test]
    fn lookup_is_monotone_and_conservatively_rounded() {
        let table = LossTable::generate();
        let mut previous = table.get(1).unwrap();
        for q in 2..65_536_u32 {
            let actual = table.get(q).unwrap();
            assert!(actual <= previous);
            let ideal = -(f64::from(q) / 65_536.0).log2() * f64::from(1_u32 << 24);
            assert!(f64::from(actual) + 1e-7 >= ideal);
            assert!(f64::from(actual) - ideal < 1.000_001);
            previous = actual;
        }
    }

    #[test]
    fn probability_charges_before_bounded_update() {
        let table = LossTable::generate();
        let mut probability = Probability::default();
        assert_eq!(table.get(probability.probability_of(true)), Some(1 << 24));
        probability.update(true, 5);
        assert_eq!(probability.probability_of_one(), 33_792);
        for _ in 0..10_000 {
            probability.update(true, 5);
        }
        assert_eq!(probability.probability_of_one(), MAX_PROBABILITY);
        for _ in 0..10_000 {
            probability.update(false, 5);
        }
        assert_eq!(probability.probability_of_one(), MIN_PROBABILITY);
    }

    #[test]
    fn lookup_digest_is_stable() {
        let first = LossTable::generate();
        let second = LossTable::generate();
        assert_eq!(first.sha256(), second.sha256());
        assert_ne!(first.sha256(), [0_u8; 32]);
    }
}
